# Generated by Django 4.2.3 on 2023-08-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.CharField(max_length=1000),
        ),
    ]
