# Generated by Django 4.2.3 on 2023-08-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_products_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_n', models.TextField(max_length=1000)),
            ],
        ),
    ]
