# Generated by Django 4.2.3 on 2023-08-06 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_likesave'),
    ]

    operations = [
        migrations.AddField(
            model_name='likesave',
            name='product_name',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='product.products'),
            preserve_default=False,
        ),
    ]
